//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BQSCusBackImageModel, UIButton;

@interface BQSBackgroundView : UIView
{
    _Bool _isShowAll;
    CDUnknownBlockType _actionBlock;
    UIButton *_showBtn;
    BQSCusBackImageModel *_backImageModel;
}

@property(retain, nonatomic) BQSCusBackImageModel *backImageModel; // @synthesize backImageModel=_backImageModel;
@property(retain, nonatomic) UIButton *showBtn; // @synthesize showBtn=_showBtn;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(nonatomic) _Bool isShowAll; // @synthesize isShowAll=_isShowAll;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic) double showWidth;
- (void)btnClick:(id)arg1;
- (void)showBtnClick;
- (void)tapHandle;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateBtns;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

