//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CKYDrawToolView, NSMutableArray, UIColor, UIImage;

@interface BQSDrawToolViewController : UIViewController
{
    _Bool _isEraser;
    _Bool _isCanGoback;
    _Bool _isCanRedo;
    double _lineWidth;
    unsigned long long _currentType;
    UIColor *_color;
    UIColor *_insideColor;
    UIColor *_shineColor;
    UIImage *_mosaicBackImage;
    UIImage *_styleBackImage;
    CKYDrawToolView *_drawToolView;
    NSMutableArray *_redoDrawToolViewArrayM;
}

@property(retain, nonatomic) NSMutableArray *redoDrawToolViewArrayM; // @synthesize redoDrawToolViewArrayM=_redoDrawToolViewArrayM;
@property(retain, nonatomic) CKYDrawToolView *drawToolView; // @synthesize drawToolView=_drawToolView;
@property(nonatomic) _Bool isCanRedo; // @synthesize isCanRedo=_isCanRedo;
@property(nonatomic) _Bool isCanGoback; // @synthesize isCanGoback=_isCanGoback;
@property(nonatomic) _Bool isEraser; // @synthesize isEraser=_isEraser;
@property(retain, nonatomic) UIImage *styleBackImage; // @synthesize styleBackImage=_styleBackImage;
@property(retain, nonatomic) UIImage *mosaicBackImage; // @synthesize mosaicBackImage=_mosaicBackImage;
@property(retain, nonatomic) UIColor *shineColor; // @synthesize shineColor=_shineColor;
@property(retain, nonatomic) UIColor *insideColor; // @synthesize insideColor=_insideColor;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) unsigned long long currentType; // @synthesize currentType=_currentType;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)goback;
- (void)redo;
- (void)changeOldDrawToolView:(id)arg1 toNewDrawToolView:(id)arg2;
- (void)updateViewInfo;
- (void)updateDrawToolViews;
- (id)getDrawModel;
- (void)viewDidLoad;
- (id)init;

@end

