//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKYMiddleBaseView.h"

#import "BQSPanHistoryViewDelegate.h"

@class BQSPanHistoryView, CKYScrawlView, NSMutableArray, NSString, UIButton;

@interface BQSPanToolView : CKYMiddleBaseView <BQSPanHistoryViewDelegate>
{
    double _btnLeftRightMargin;
    NSMutableArray *_scrawlHistory;
    UIButton *_historyBtn;
    BQSPanHistoryView *_panHistoryView;
    CKYScrawlView *_scrawlView;
}

@property(retain, nonatomic) CKYScrawlView *scrawlView; // @synthesize scrawlView=_scrawlView;
@property(retain, nonatomic) BQSPanHistoryView *panHistoryView; // @synthesize panHistoryView=_panHistoryView;
@property(retain, nonatomic) UIButton *historyBtn; // @synthesize historyBtn=_historyBtn;
@property(retain, nonatomic) NSMutableArray *scrawlHistory; // @synthesize scrawlHistory=_scrawlHistory;
@property(nonatomic) double btnLeftRightMargin; // @synthesize btnLeftRightMargin=_btnLeftRightMargin;
- (void).cxx_destruct;
- (void)panHistoryViewDidSelectItem:(id)arg1;
- (void)rightBtnClick:(id)arg1;
- (void)leftBtnClick:(id)arg1;
- (void)getDrawModel:(id)arg1;
- (void)initNotification;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

