//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView;

@interface BQSPanBoardTopView : UIView
{
    id <BQSPanBoardTopViewDelegate> _delegate;
    UIButton *_nextButton;
    UIImageView *_nextImageView;
}

@property(retain, nonatomic) UIImageView *nextImageView; // @synthesize nextImageView=_nextImageView;
@property(retain, nonatomic) UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak id <BQSPanBoardTopViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)nextBtnClick;
- (void)backBtnClick;
- (void)hiddenNextButton;
- (void)showNextButton;
- (void)initConfig;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

