//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BQSCusBackImageModel, NSMutableArray;

@interface CKYCustomizingModel : NSObject
{
    _Bool _isFromePreview;
    BQSCusBackImageModel *_backInfoModel;
    NSMutableArray *_itemArray;
    double _width;
    double _height;
    long long _originId;
    long long _originalId;
}

+ (id)customizingModelWithDict:(id)arg1;
+ (id)customizingModelWithWebPPath:(id)arg1;
+ (void)clearCache;
+ (id)customizingModelGetCache;
@property(nonatomic) _Bool isFromePreview; // @synthesize isFromePreview=_isFromePreview;
@property(nonatomic) long long originalId; // @synthesize originalId=_originalId;
@property(nonatomic) long long originId; // @synthesize originId=_originId;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(retain, nonatomic) NSMutableArray *itemArray; // @synthesize itemArray=_itemArray;
@property(retain, nonatomic) BQSCusBackImageModel *backInfoModel; // @synthesize backInfoModel=_backInfoModel;
- (void).cxx_destruct;
- (id)copyCustommizingModel;
- (id)getDict;

@end

