//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class BQSTextStyleModel, NSString;

@interface CKYRotationViewItem : NSObject <NSCoding>
{
    _Bool _turnOverH;
    _Bool _turnOverV;
    NSString *_text;
    NSString *_textFontName;
    NSString *_textFontPath;
    double _textFontSize;
    BQSTextStyleModel *_textStyleModel;
    NSString *_imageURL;
    long long _contentViewType;
    double _angle;
    double _xScale;
    double _yScale;
    double _toCenterYMargin;
    long long _index;
    long long _vMoveBtnPositionType;
    long long _hMoveBtnPositionType;
    struct CGPoint _center;
    struct CGSize _size;
}

+ (id)itemWithDict:(id)arg1;
@property(nonatomic) long long hMoveBtnPositionType; // @synthesize hMoveBtnPositionType=_hMoveBtnPositionType;
@property(nonatomic) long long vMoveBtnPositionType; // @synthesize vMoveBtnPositionType=_vMoveBtnPositionType;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) _Bool turnOverV; // @synthesize turnOverV=_turnOverV;
@property(nonatomic) _Bool turnOverH; // @synthesize turnOverH=_turnOverH;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) double toCenterYMargin; // @synthesize toCenterYMargin=_toCenterYMargin;
@property(nonatomic) struct CGPoint center; // @synthesize center=_center;
@property(nonatomic) double yScale; // @synthesize yScale=_yScale;
@property(nonatomic) double xScale; // @synthesize xScale=_xScale;
@property(nonatomic) double angle; // @synthesize angle=_angle;
@property(nonatomic) long long contentViewType; // @synthesize contentViewType=_contentViewType;
@property(copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) BQSTextStyleModel *textStyleModel; // @synthesize textStyleModel=_textStyleModel;
@property(nonatomic) double textFontSize; // @synthesize textFontSize=_textFontSize;
@property(copy, nonatomic) NSString *textFontPath; // @synthesize textFontPath=_textFontPath;
@property(copy, nonatomic) NSString *textFontName; // @synthesize textFontName=_textFontName;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyRotationViewItem;
- (id)initWithDict:(id)arg1;
- (id)getDict;
- (id)init;

@end

