//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface CKYStyleModel : NSObject
{
    UIColor *_miaobianColor;
    double _miaobianSize;
    double _miaobianAlpha;
    UIColor *_textColor;
    double _textColorSize;
    double _textAlpha;
    UIColor *_startColor;
    UIColor *_endColor;
}

+ (id)sytleModelWithDict:(id)arg1;
@property(retain, nonatomic) UIColor *endColor; // @synthesize endColor=_endColor;
@property(retain, nonatomic) UIColor *startColor; // @synthesize startColor=_startColor;
@property(nonatomic) double textAlpha; // @synthesize textAlpha=_textAlpha;
@property(nonatomic) double textColorSize; // @synthesize textColorSize=_textColorSize;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(nonatomic) double miaobianAlpha; // @synthesize miaobianAlpha=_miaobianAlpha;
@property(nonatomic) double miaobianSize; // @synthesize miaobianSize=_miaobianSize;
@property(retain, nonatomic) UIColor *miaobianColor; // @synthesize miaobianColor=_miaobianColor;
- (void).cxx_destruct;
- (id)copyStyleModel;
- (id)init;
- (id)getDict;

@end

