//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer, UIColor;

@interface CKYBorderView : UIView
{
    UIColor *_borderColor;
    UIView *_rbView;
    UIView *_rtView;
    UIView *_ltView;
    UIView *_lbView;
    UIView *_topView;
    UIView *_leftView;
    UIView *_bottomView;
    UIView *_rightView;
    CAShapeLayer *_shapeLayer;
}

@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(retain, nonatomic) UIView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIView *leftView; // @synthesize leftView=_leftView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIView *lbView; // @synthesize lbView=_lbView;
@property(retain, nonatomic) UIView *ltView; // @synthesize ltView=_ltView;
@property(retain, nonatomic) UIView *rtView; // @synthesize rtView=_rtView;
@property(retain, nonatomic) UIView *rbView; // @synthesize rbView=_rbView;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGPoint)getBottomPoint;
- (struct CGPoint)getRightPoint;
- (struct CGPoint)getLeftPoint;
- (struct CGPoint)getTopPoint;
- (struct CGPoint)getLeftBottomPoint;
- (struct CGPoint)getLeftTopPoint;
- (struct CGPoint)getRightTopPoint;
- (struct CGPoint)getRightBottomPoint;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;

@end

