//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKYDrawBaseView.h"

@class CALayer, CAShapeLayer, UIImage;

@interface CKYDrawStylePanView : CKYDrawBaseView
{
    UIImage *_image;
    CALayer *_imageLayer;
    CAShapeLayer *_shapeLayer;
}

@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(retain, nonatomic) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)setPath:(id)arg1;
- (void)setLineWidth:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

