//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKYDrawBaseView.h"

@class CAShapeLayer, UIColor;

@interface CKYDrawPanView : CKYDrawBaseView
{
    UIColor *_color;
    CAShapeLayer *_currentLayer;
}

@property(retain, nonatomic) CAShapeLayer *currentLayer; // @synthesize currentLayer=_currentLayer;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)creatLayer;
- (void)goback;
- (void)redo;
- (void)setLineWidth:(double)arg1;
- (void)touchEnd;
- (void)setPath:(id)arg1;
- (id)getLastPath;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;

@end

