//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKYDrawBaseView.h"

@class CALayer, UIColor, UIImage;

@interface CKYDrawShinePanView : CKYDrawBaseView
{
    double _drawOpacity;
    double _airBrushFlow;
    CALayer *drawLayer;
    UIImage *mainImage;
    UIImage *drawImage;
    UIImage *airBrushImage;
    UIColor *_drawColor;
}

@property(retain, nonatomic) UIColor *drawColor; // @synthesize drawColor=_drawColor;
- (void).cxx_destruct;
- (void)setSketch:(id)arg1;
- (id)getSketch;
- (void)clearToColor:(id)arg1;
- (void)airBrushTouchesEnded;
- (id)image:(id)arg1 rotation:(long long)arg2;
- (void)drawAirBrushImage;
- (void)commitDrawingWithOpacity:(double)arg1;
- (void)randomAirBrushImage;
- (void)drawImage:(id)arg1 from:(struct CGPoint)arg2 to:(struct CGPoint)arg3;
- (void)drawImage:(id)arg1 at:(struct CGPoint)arg2;
@property double airBrushFlow;
@property double drawOpacity;
- (void)goback;
- (void)redo;
- (void)touchEnd;
- (void)setPath:(id)arg1;
- (void)layoutSubviews;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;

@end

