//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CKYDrawBaseView, CKYEraserToolView, UIBezierPath, UIImage, UIImageView;

@interface CKYDrawToolView : UIView
{
    _Bool _isEraser;
    double _panLineWidth;
    double _eraserLineWidth;
    CKYDrawToolView *_oldDrawToolView;
    UIImage *_image;
    UIImage *_backImage;
    UIBezierPath *_path;
    UIImageView *_imageView;
    CKYDrawBaseView *_currentView;
    CKYEraserToolView *_eraserToolView;
    CKYEraserToolView *_redoEraserToolView;
}

@property(retain, nonatomic) CKYEraserToolView *redoEraserToolView; // @synthesize redoEraserToolView=_redoEraserToolView;
@property(retain, nonatomic) CKYEraserToolView *eraserToolView; // @synthesize eraserToolView=_eraserToolView;
@property(retain, nonatomic) CKYDrawBaseView *currentView; // @synthesize currentView=_currentView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIBezierPath *path; // @synthesize path=_path;
@property(retain, nonatomic) UIImage *backImage; // @synthesize backImage=_backImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) CKYDrawToolView *oldDrawToolView; // @synthesize oldDrawToolView=_oldDrawToolView;
@property(nonatomic) double eraserLineWidth; // @synthesize eraserLineWidth=_eraserLineWidth;
@property(nonatomic) double panLineWidth; // @synthesize panLineWidth=_panLineWidth;
@property(nonatomic) _Bool isEraser; // @synthesize isEraser=_isEraser;
- (void).cxx_destruct;
- (void)drawToolTouchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)drawToolTouchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)drawToolTouchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)drawToolTouchesBegan:(id)arg1 withEvent:(id)arg2;
- (struct CGRect)getPathMaxRect;
- (_Bool)isAllRedo;
- (_Bool)isHavePath;
- (_Bool)isHaveEraser;
- (void)goback;
- (void)redo;
- (id)getImage;
- (unsigned long long)currentDrawViewType;
- (void)addSubviewType:(unsigned long long)arg1 withLineWidth:(double)arg2 color:(id)arg3 insideColor:(id)arg4 shineColor:(id)arg5 mosaicImage:(id)arg6 backgroundImage:(id)arg7 isEraser:(_Bool)arg8;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;

@end

