//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIBezierPath;

@interface CKYDrawBaseView : UIView
{
    double _lineWidth;
    UIBezierPath *_path;
    unsigned long long _type;
    NSMutableArray *_paths;
    NSMutableArray *_redoPaths;
}

@property(retain, nonatomic) NSMutableArray *redoPaths; // @synthesize redoPaths=_redoPaths;
@property(retain, nonatomic) NSMutableArray *paths; // @synthesize paths=_paths;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) UIBezierPath *path; // @synthesize path=_path;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
- (void).cxx_destruct;
- (struct CGRect)getPathRect;
- (void)touchEnd;
- (void)goback;
- (void)redo;
- (id)getRedoPath;
- (id)getGobackPath;
- (id)getLastPath;
- (id)initWithFrame:(struct CGRect)arg1;

@end

