//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKYRotationView.h"

@class UIImage<YYAnimatedImage>;

@interface CKYImageRotationView : CKYRotationView
{
    UIImage<YYAnimatedImage> *_aniImage;
}

+ (id)rotationViewWithItem:(id)arg1;
@property(retain, nonatomic) UIImage<YYAnimatedImage> *aniImage; // @synthesize aniImage=_aniImage;
- (void).cxx_destruct;
- (void)setEleTime:(CDStruct_1b6d18a9)arg1 allTime:(CDStruct_1b6d18a9)arg2;
- (void)endSynchor;
- (void)beganSynchro;

@end

