//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray;

@interface CKYMainToolView : UIView
{
    id <CKYMainToolViewDelegate> _delegate;
    NSArray *_buttonImages;
    NSMutableArray *_buttonArray;
    UIView *_indicatorView;
    long long _currentIndex;
}

@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) UIView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) NSMutableArray *buttonArray; // @synthesize buttonArray=_buttonArray;
@property(retain, nonatomic) NSArray *buttonImages; // @synthesize buttonImages=_buttonImages;
@property(nonatomic) __weak id <CKYMainToolViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)moveToIndex:(long long)arg1;
- (void)tapHandle:(id)arg1;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;

@end

