//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "BQSPanSlideSelectViewDelegate.h"
#import "CKYPickerColorViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class BQSPanSlideSelectView, CKYPickerColorView, NSArray, NSString, UICollectionView, UIColor, UIImageView;

@interface CKYScrawlView : UIView <BQSPanSlideSelectViewDelegate, CKYPickerColorViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource>
{
    CKYPickerColorView *_pickerColorView;
    _Bool _isNeedDefaultSelect;
    NSArray *_colorArray;
    NSArray *_styleImageArray;
    UIImageView *_selectStatusView;
    UICollectionView *_middleCollectionView;
    UICollectionView *_bottomCollectionView;
    BQSPanSlideSelectView *_slideSelectView;
    UIColor *_color;
}

@property(nonatomic) _Bool isNeedDefaultSelect; // @synthesize isNeedDefaultSelect=_isNeedDefaultSelect;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) BQSPanSlideSelectView *slideSelectView; // @synthesize slideSelectView=_slideSelectView;
@property(retain, nonatomic) UICollectionView *bottomCollectionView; // @synthesize bottomCollectionView=_bottomCollectionView;
@property(retain, nonatomic) UICollectionView *middleCollectionView; // @synthesize middleCollectionView=_middleCollectionView;
@property(retain, nonatomic) UIImageView *selectStatusView; // @synthesize selectStatusView=_selectStatusView;
@property(retain, nonatomic) NSArray *styleImageArray; // @synthesize styleImageArray=_styleImageArray;
@property(retain, nonatomic) NSArray *colorArray; // @synthesize colorArray=_colorArray;
- (void).cxx_destruct;
- (void)pickerColorView:(id)arg1 getColor:(id)arg2;
- (void)pickerColorViewGoback:(id)arg1;
- (void)panSlideSelectView:(id)arg1 didChangeValur:(double)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)initConfig;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

