//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface CKYTopToolView : UIView
{
    id <CKYTopToolViewDelegate> _delegate;
}

@property(nonatomic) __weak id <CKYTopToolViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)nextBtnClick:(id)arg1;
- (void)shareBtnClick:(id)arg1;
- (void)backBtnClick:(id)arg1;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1;

@end

