//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKYRotationView.h"

@interface CKYTextboxRotationView : CKYRotationView
{
    _Bool _isBegin;
    double _textAniDuration;
}

+ (id)rotationViewWithItem:(id)arg1;
@property(nonatomic) _Bool isBegin; // @synthesize isBegin=_isBegin;
@property(nonatomic) double textAniDuration; // @synthesize textAniDuration=_textAniDuration;
- (void)updateDuration:(id)arg1;
- (void)setEleTime:(CDStruct_1b6d18a9)arg1 allTime:(CDStruct_1b6d18a9)arg2;
- (void)endSynchor;
- (void)beganSynchro;
- (void)updataColor:(id)arg1;
- (void)updataStyle:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

