//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKYMiddleBaseView.h"

@class UIScrollView, UIView<BQSTextDelegate>;

@interface CKYTextToolView : CKYMiddleBaseView
{
    UIView<BQSTextDelegate> *_currentShowView;
    UIScrollView *_scrollView;
    struct CGPoint _labelCenter;
    struct CGPoint _btnCenter;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView<BQSTextDelegate> *currentShowView; // @synthesize currentShowView=_currentShowView;
@property(nonatomic) struct CGPoint btnCenter; // @synthesize btnCenter=_btnCenter;
@property(nonatomic) struct CGPoint labelCenter; // @synthesize labelCenter=_labelCenter;
- (void).cxx_destruct;
- (void)reset;
- (void)btnClick:(id)arg1;
- (void)updateBtnsStatus;
- (void)updateDuration:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)initConfig;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

