//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BQSAuthorizationManagerDelegate.h"
#import "BQSEyedropperViewDelegate.h"
#import "BQSPanBoardTopViewDelegate.h"
#import "BQSShareViewDelegate.h"
#import "CKYAddTextViewDelegate.h"
#import "CKYCustomizingViewControllerDelegate.h"
#import "CKYPhotoGalleryViewControllerDelegate.h"
#import "CKYToolViewDelegate.h"
#import "CKYTopToolViewDelegate.h"

@class BQSDrawToolViewController, BQSEyedropperView, BQSHitTestView, BQSPanBoardTopView, CKYCustomizingModel, CKYCustomizingViewController, CKYToolView, CKYTopToolView, NSString, UINavigationController;

@interface BQSMakeViewController : UIViewController <CKYCustomizingViewControllerDelegate, CKYAddTextViewDelegate, CKYTopToolViewDelegate, BQSPanBoardTopViewDelegate, CKYToolViewDelegate, BQSEyedropperViewDelegate, BQSShareViewDelegate, CKYPhotoGalleryViewControllerDelegate, BQSAuthorizationManagerDelegate>
{
    _Bool _isPrivate;
    _Bool _notRecommend;
    _Bool _isNeedActionHit;
    CKYCustomizingModel *_customizingModel;
    NSString *_topicDesc;
    long long _draftsID;
    id <BQSMakeViewControllerDelegate> _delegate;
    CKYCustomizingViewController *_customizingVC;
    BQSDrawToolViewController *_drawToolVC;
    CKYToolView *_toolView;
    CKYTopToolView *_topToolView;
    BQSPanBoardTopView *_boardTopView;
    BQSEyedropperView *_eyedropperView;
    UINavigationController *_materialNaVC;
    BQSHitTestView *_hitTestView;
}

@property(nonatomic) _Bool isNeedActionHit; // @synthesize isNeedActionHit=_isNeedActionHit;
@property(retain, nonatomic) BQSHitTestView *hitTestView; // @synthesize hitTestView=_hitTestView;
@property(retain, nonatomic) UINavigationController *materialNaVC; // @synthesize materialNaVC=_materialNaVC;
@property(retain, nonatomic) BQSEyedropperView *eyedropperView; // @synthesize eyedropperView=_eyedropperView;
@property(retain, nonatomic) BQSPanBoardTopView *boardTopView; // @synthesize boardTopView=_boardTopView;
@property(retain, nonatomic) CKYTopToolView *topToolView; // @synthesize topToolView=_topToolView;
@property(retain, nonatomic) CKYToolView *toolView; // @synthesize toolView=_toolView;
@property(retain, nonatomic) BQSDrawToolViewController *drawToolVC; // @synthesize drawToolVC=_drawToolVC;
@property(retain, nonatomic) CKYCustomizingViewController *customizingVC; // @synthesize customizingVC=_customizingVC;
@property(nonatomic) __weak id <BQSMakeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool notRecommend; // @synthesize notRecommend=_notRecommend;
@property(nonatomic) _Bool isPrivate; // @synthesize isPrivate=_isPrivate;
@property(nonatomic) long long draftsID; // @synthesize draftsID=_draftsID;
@property(copy, nonatomic) NSString *topicDesc; // @synthesize topicDesc=_topicDesc;
@property(retain, nonatomic) CKYCustomizingModel *customizingModel; // @synthesize customizingModel=_customizingModel;
- (void).cxx_destruct;
- (void)authorizationManagerDidGetCameraAuthor;
- (_Bool)photoGalleryIsHandleGIF:(id)arg1;
- (void)didClickEmail:(id)arg1;
- (void)didClickMessage:(id)arg1;
- (void)didClickSystemShare:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)toolViewClear;
- (void)toolViewRedo;
- (void)toolViewGoback;
- (void)topToolViewDidShare:(id)arg1;
- (void)topToolViewDidNext:(id)arg1;
- (void)topToolViewDidBack:(id)arg1;
- (void)addTextView:(id)arg1 changeText:(id)arg2;
- (void)addTextView:(id)arg1 addText:(id)arg2;
- (void)customizingViewHiddenDelete;
- (void)customizingViewShowDelete;
- (void)customizingViewWillChangeText:(id)arg1;
- (void)customizingViewControllerDidCustomizing:(long long)arg1;
- (void)panBoardTopViewDidBack:(id)arg1;
- (void)panBoardTopViewDidNext:(id)arg1;
- (void)eyedropperView:(id)arg1 endSelectPoint:(struct CGPoint)arg2;
- (void)eyedropperView:(id)arg1 moveSelectPoint:(struct CGPoint)arg2;
- (void)eyedropperView:(id)arg1 beginSelectPoint:(struct CGPoint)arg2;
- (void)toolViewEyedropperHidden:(id)arg1;
- (void)toolViewEyedropperClick:(id)arg1;
- (void)panToolViewAddDrawModel:(id)arg1;
- (void)addDrawModel:(id)arg1;
- (void)panToolViewHidden;
- (void)panToolViewShow;
- (void)materialToolViewGetIamge:(id)arg1;
- (void)materialToolShowPhoto;
- (void)materialToolExit:(id)arg1;
- (void)materialToolAddMaterial:(id)arg1;
- (void)materialToolShow:(id)arg1;
- (void)backgroundToolShowPhoto;
- (void)backgroundToolShowCamera;
- (void)textToolViewChangeTextBox:(id)arg1;
- (void)textToolViewWillDownFont:(id)arg1;
- (void)textToolViewChangeTextAni:(id)arg1;
- (void)textToolViewChangeTextFont:(id)arg1;
- (void)textToolViewAddText;
- (void)doneNeedActionHit;
- (void)hitTestViewAction;
- (void)initNotification;
- (void)dealloc;
- (void)initConfig;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

