//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBezierPath.h"

@class UIColor;

@interface CKYBezierPath : UIBezierPath
{
    UIColor *_pathColor;
}

@property(retain, nonatomic) UIColor *pathColor; // @synthesize pathColor=_pathColor;
- (void).cxx_destruct;

@end

