//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKYColorBoardView;

@protocol CKYColorBoardViewDelegate <NSObject>

@optional
- (void)colorBoardViewEndGetColor:(CKYColorBoardView *)arg1;
- (void)colorBoardViewBeginGetColor:(CKYColorBoardView *)arg1;
- (void)colorBoardView:(CKYColorBoardView *)arg1 getCurrentColorR:(double)arg2 G:(double)arg3 B:(double)arg4 point:(struct CGPoint)arg5;
@end

