//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CKYGif : NSObject
{
}

+ (void)createfromAVAsset:(id)arg1 withFrameCount:(long long)arg2 delayTime:(float)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)createfromURL:(id)arg1 withFrameCount:(long long)arg2 delayTime:(float)arg3 completion:(CDUnknownBlockType)arg4;
+ (id)exportGifImages:(id)arg1 delays:(id)arg2 loopCount:(unsigned long long)arg3;
+ (id)getGifInfoWithData:(id)arg1;
+ (id)imageArrayWithGifData:(id)arg1;
+ (id)imageWithGifData:(id)arg1 andIndex:(unsigned long long)arg2;
+ (id)delayArrayWithGifData:(id)arg1;
+ (double)delayTimeWithGifData:(id)arg1 andIndex:(unsigned long long)arg2;
+ (id)delayArrayWithSource:(struct CGImageSource *)arg1;
+ (double)delayTimeWithSource:(struct CGImageSource *)arg1 andIndex:(unsigned long long)arg2;
+ (id)imageWithSource:(struct CGImageSource *)arg1 andIndex:(unsigned long long)arg2;
+ (_Bool)isGifWithData:(id)arg1;

@end

