//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKYTopToolView;

@protocol CKYTopToolViewDelegate <NSObject>
- (void)topToolViewDidShare:(CKYTopToolView *)arg1;
- (void)topToolViewDidNext:(CKYTopToolView *)arg1;
- (void)topToolViewDidBack:(CKYTopToolView *)arg1;
@end

