/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

TestView *__cdecl -[TestView initWithFrame:](TestView *self, SEL, CGRect);
void __cdecl -[TestView configMethod](TestView *self, SEL);
double __cdecl -[TestView origin_x](TestView *self, SEL);
void __cdecl -[TestView setOrigin_x:](TestView *self, SEL, double);
double __cdecl -[TestView origin_y](TestView *self, SEL);
void __cdecl -[TestView setOrigin_y:](TestView *self, SEL, double);
double __cdecl -[TestView size_width](TestView *self, SEL);
void __cdecl -[TestView setSize_width:](TestView *self, SEL, double);
double __cdecl -[TestView size_height](TestView *self, SEL);
void __cdecl -[TestView setSize_height:](TestView *self, SEL, double);
CGPoint __cdecl -[TestView centerPoint](TestView *self, SEL);
void __cdecl -[TestView setCenterPoint:](TestView *self, SEL, CGPoint);
double __cdecl -[TestView center_x](TestView *self, SEL);
void __cdecl -[TestView setCenter_x:](TestView *self, SEL, double);
double __cdecl -[TestView center_y](TestView *self, SEL);
void __cdecl -[TestView setCenter_y:](TestView *self, SEL, double);
double __cdecl -[TestView origin](TestView *self, SEL);
void __cdecl -[TestView setOrigin:](TestView *self, SEL, double);
double __cdecl -[TestView maxX](TestView *self, SEL);
void __cdecl -[TestView setMaxX:](TestView *self, SEL, double);
void __cdecl -[ViewController viewDidLoad](ViewController *self, SEL);
void __cdecl -[ViewController didReceiveMemoryWarning](ViewController *self, SEL);
__int64 start();
bool __cdecl -[AppDelegate application:didFinishLaunchingWithOptions:](AppDelegate *self, SEL, id, id);
UIWindow *__cdecl -[AppDelegate window](AppDelegate *self, SEL);
void __cdecl -[AppDelegate setWindow:](AppDelegate *self, SEL, id);
void __cdecl -[AppDelegate .cxx_destruct](AppDelegate *self, SEL);
__int64 NSStringFromClass();
__int64 UIApplicationMain();
__int64 objc_autoreleasePoolPop();
__int64 objc_autoreleasePoolPush();
void *objc_msgSend(void *, const char *, ...);
void *objc_msgSendSuper2(void *, const char *, ...); // idb
__int64 objc_release();
__int64 objc_retainAutoreleasedReturnValue();
void *objc_msgSend_ptr(void *, const char *, ...); // idb
void *objc_msgSendSuper2_ptr(void *, const char *, ...); // idb
// __int64 _NSStringFromClass(void); weak
// __int64 _objc_autoreleasePoolPop(void); weak
// __int64 _objc_autoreleasePoolPush(void); weak
// void *_objc_msgSend(void *, const char *, ...); idb
// void *_objc_msgSendSuper2(void *, const char *, ...); idb
// __int64 _objc_release(void); weak
// __int64 _objc_retainAutoreleasedReturnValue(void); weak
// __int64 __fastcall _objc_storeStrong(_QWORD, _QWORD); weak
// __int64 _UIApplicationMain(void); weak

//-------------------------------------------------------------------------
// Data declarations

__objc2_class OBJC_CLASS___TestView =
{
  &OBJC_METACLASS___TestView,
  &OBJC_CLASS___UIView,
  &_objc_empty_cache,
  NULL,
  &TestView__classData
}; // weak
__objc2_class OBJC_CLASS___ViewController =
{
  &OBJC_METACLASS___ViewController,
  &OBJC_CLASS___UIViewController,
  &_objc_empty_cache,
  NULL,
  &ViewController__classData
}; // weak
__objc2_class OBJC_CLASS___AppDelegate =
{
  &OBJC_METACLASS___AppDelegate,
  &OBJC_CLASS___UIResponder,
  &_objc_empty_cache,
  NULL,
  &AppDelegate__classData
}; // weak


//----- (00000001000063B8) ----------------------------------------------------
// local variable allocation has failed, the output may be wrong!
TestView *__cdecl -[TestView initWithFrame:](TestView *self, SEL a2, CGRect a3)
{
  TestView *v3; // x0
  TestView *v4; // x19
  TestView *v6; // [xsp+0h] [xbp-20h]
  __objc2_class *v7; // [xsp+8h] [xbp-18h]

  v6 = self;
  v7 = &OBJC_CLASS___TestView;
  v3 = (TestView *)objc_msgSendSuper2(
                     &v6,
                     "initWithFrame:",
                     a3.var0.var0,
                     a3.var0.var1,
                     a3.var1.var0,
                     a3.var1.var1,
                     self,
                     &OBJC_CLASS___TestView);
  v4 = v3;
  if ( v3 )
    -[TestView configMethod](v3, "configMethod");
  return v4;
}
// 1000063B8: fragmented variable at 0:d0.8,8:d1.8,16:d2.8,24:d3.8 may be wrong
// 1000091A8: using guessed type __objc2_class OBJC_CLASS___TestView;

//----- (0000000100006414) ----------------------------------------------------
void __cdecl -[TestView configMethod](TestView *self, SEL a2)
{
  TestView *v2; // x19
  double v3; // d3
  double v4; // d1
  double v5; // d2
  double v6; // d1
  double v7; // d0
  double v8; // d8
  double v9; // d2

  v2 = self;
  objc_msgSend(self, "frame");
  -[TestView setSize_height:](v2, "setSize_height:", v3);
  objc_msgSend(v2, "frame");
  -[TestView setOrigin_y:](v2, "setOrigin_y:", v4);
  objc_msgSend(v2, "frame");
  -[TestView setSize_width:](v2, "setSize_width:", v5);
  objc_msgSend(v2, "center");
  -[TestView setCenter_y:](v2, "setCenter_y:", v6);
  objc_msgSend(v2, "center");
  -[TestView setCenterPoint:](v2, "setCenterPoint:");
  objc_msgSend(v2, "frame");
  -[TestView setOrigin_x:](v2, "setOrigin_x:");
  objc_msgSend(v2, "center");
  -[TestView setCenter_x:](v2, "setCenter_x:");
  objc_msgSend(v2, "center");
  v8 = v7;
  objc_msgSend(v2, "frame");
  -[TestView setMaxX:](v2, "setMaxX:", v8 + v9);
  -[TestView setOrigin:](v2, "setOrigin:", 0.0);
}

//----- (0000000100006560) ----------------------------------------------------
double __cdecl -[TestView origin_x](TestView *self, SEL a2)
{
  return self->_origin_x;
}

//----- (0000000100006570) ----------------------------------------------------
void __cdecl -[TestView setOrigin_x:](TestView *self, SEL a2, double a3)
{
  self->_origin_x = a3;
}

//----- (0000000100006580) ----------------------------------------------------
double __cdecl -[TestView origin_y](TestView *self, SEL a2)
{
  return self->_origin_y;
}

//----- (0000000100006590) ----------------------------------------------------
void __cdecl -[TestView setOrigin_y:](TestView *self, SEL a2, double a3)
{
  self->_origin_y = a3;
}

//----- (00000001000065A0) ----------------------------------------------------
double __cdecl -[TestView size_width](TestView *self, SEL a2)
{
  return self->_size_width;
}

//----- (00000001000065B0) ----------------------------------------------------
void __cdecl -[TestView setSize_width:](TestView *self, SEL a2, double a3)
{
  self->_size_width = a3;
}

//----- (00000001000065C0) ----------------------------------------------------
double __cdecl -[TestView size_height](TestView *self, SEL a2)
{
  return self->_size_height;
}

//----- (00000001000065D0) ----------------------------------------------------
void __cdecl -[TestView setSize_height:](TestView *self, SEL a2, double a3)
{
  self->_size_height = a3;
}

//----- (00000001000065E0) ----------------------------------------------------
CGPoint __cdecl -[TestView centerPoint](TestView *self, SEL a2)
{
  double v2; // d0
  double v3; // d1
  CGPoint result; // 0:d0.8,8:d1.8

  v2 = self->_centerPoint.var0;
  v3 = self->_centerPoint.var1;
  result.var1 = v3;
  result.var0 = v2;
  return result;
}

//----- (00000001000065F4) ----------------------------------------------------
// local variable allocation has failed, the output may be wrong!
void __cdecl -[TestView setCenterPoint:](TestView *self, SEL a2, CGPoint a3)
{
  double *v3; // x8

  v3 = &self->_centerPoint.var0;
  *v3 = a3.var0;
  v3[1] = a3.var1;
}
// 1000065F4: fragmented variable at 0:d0.8,8:d1.8 may be wrong

//----- (0000000100006608) ----------------------------------------------------
double __cdecl -[TestView center_x](TestView *self, SEL a2)
{
  return self->_center_x;
}

//----- (0000000100006618) ----------------------------------------------------
void __cdecl -[TestView setCenter_x:](TestView *self, SEL a2, double a3)
{
  self->_center_x = a3;
}

//----- (0000000100006628) ----------------------------------------------------
double __cdecl -[TestView center_y](TestView *self, SEL a2)
{
  return self->_center_y;
}

//----- (0000000100006638) ----------------------------------------------------
void __cdecl -[TestView setCenter_y:](TestView *self, SEL a2, double a3)
{
  self->_center_y = a3;
}

//----- (0000000100006648) ----------------------------------------------------
double __cdecl -[TestView origin](TestView *self, SEL a2)
{
  return self->_origin;
}

//----- (0000000100006658) ----------------------------------------------------
void __cdecl -[TestView setOrigin:](TestView *self, SEL a2, double a3)
{
  self->_origin = a3;
}

//----- (0000000100006668) ----------------------------------------------------
double __cdecl -[TestView maxX](TestView *self, SEL a2)
{
  return self->_maxX;
}

//----- (0000000100006678) ----------------------------------------------------
void __cdecl -[TestView setMaxX:](TestView *self, SEL a2, double a3)
{
  self->_maxX = a3;
}

//----- (0000000100006688) ----------------------------------------------------
void __cdecl -[ViewController viewDidLoad](ViewController *self, SEL a2)
{
  ViewController *v2; // x19
  TestView *v3; // x20
  void *v4; // x0
  ViewController *v5; // [xsp+0h] [xbp-20h]
  __objc2_class *v6; // [xsp+8h] [xbp-18h]

  v2 = self;
  v5 = self;
  v6 = &OBJC_CLASS___ViewController;
  objc_msgSendSuper2(&v5, "viewDidLoad", self, &OBJC_CLASS___ViewController);
  v3 = objc_msgSend(&OBJC_CLASS___TestView, "new");
  objc_msgSend(v3, "setFrame:", 0.0, 0.0);
  objc_msgSend(v2, "view");
  v4 = (void *)objc_retainAutoreleasedReturnValue();
  objc_msgSend(v4, "addSubview:", v3);
  objc_release();
  objc_release();
}
// 1000091A8: using guessed type __objc2_class OBJC_CLASS___TestView;
// 1000091F8: using guessed type __objc2_class OBJC_CLASS___ViewController;

//----- (0000000100006740) ----------------------------------------------------
void __cdecl -[ViewController didReceiveMemoryWarning](ViewController *self, SEL a2)
{
  ViewController *v2; // [xsp+0h] [xbp-10h]
  __objc2_class *v3; // [xsp+8h] [xbp-8h]

  v2 = self;
  v3 = &OBJC_CLASS___ViewController;
  objc_msgSendSuper2(&v2, "didReceiveMemoryWarning", self, &OBJC_CLASS___ViewController);
}
// 1000091F8: using guessed type __objc2_class OBJC_CLASS___ViewController;

//----- (0000000100006778) ----------------------------------------------------
__int64 start()
{
  __int64 v0; // x19

  objc_autoreleasePoolPush();
  objc_msgSend(&OBJC_CLASS___AppDelegate, "class");
  NSStringFromClass();
  objc_retainAutoreleasedReturnValue();
  v0 = UIApplicationMain();
  objc_release();
  objc_autoreleasePoolPop();
  return v0;
}
// 100009270: using guessed type __objc2_class OBJC_CLASS___AppDelegate;

//----- (00000001000067F8) ----------------------------------------------------
bool __cdecl -[AppDelegate application:didFinishLaunchingWithOptions:](AppDelegate *self, SEL a2, id a3, id a4)
{
  return 1;
}

//----- (0000000100006814) ----------------------------------------------------
UIWindow *__cdecl -[AppDelegate window](AppDelegate *self, SEL a2)
{
  return self->_window;
}

//----- (0000000100006824) ----------------------------------------------------
void __cdecl -[AppDelegate setWindow:](AppDelegate *self, SEL a2, id a3)
{
  _objc_storeStrong(&self->_window, a3);
}
// 1000093A8: using guessed type __int64 __fastcall _objc_storeStrong(_QWORD, _QWORD);

//----- (0000000100006838) ----------------------------------------------------
void __cdecl -[AppDelegate .cxx_destruct](AppDelegate *self, SEL a2)
{
  _objc_storeStrong(&self->_window, 0LL);
}
// 1000093A8: using guessed type __int64 __fastcall _objc_storeStrong(_QWORD, _QWORD);

//----- (000000010000684C) ----------------------------------------------------
__int64 NSStringFromClass()
{
  return _NSStringFromClass();
}
// 100009360: using guessed type __int64 _NSStringFromClass(void);

//----- (0000000100006858) ----------------------------------------------------
__int64 UIApplicationMain()
{
  return _UIApplicationMain();
}
// 1000093E8: using guessed type __int64 _UIApplicationMain(void);

//----- (0000000100006864) ----------------------------------------------------
__int64 objc_autoreleasePoolPop()
{
  return _objc_autoreleasePoolPop();
}
// 100009378: using guessed type __int64 _objc_autoreleasePoolPop(void);

//----- (0000000100006870) ----------------------------------------------------
__int64 objc_autoreleasePoolPush()
{
  return _objc_autoreleasePoolPush();
}
// 100009380: using guessed type __int64 _objc_autoreleasePoolPush(void);

//----- (000000010000687C) ----------------------------------------------------
void *objc_msgSend(void *a1, const char *a2, ...)
{
  return _objc_msgSend(a1, a2);
}

//----- (0000000100006888) ----------------------------------------------------
void *objc_msgSendSuper2(void *a1, const char *a2, ...)
{
  return _objc_msgSendSuper2(a1, a2);
}

//----- (0000000100006894) ----------------------------------------------------
__int64 objc_release()
{
  return _objc_release();
}
// 100009398: using guessed type __int64 _objc_release(void);

//----- (00000001000068A0) ----------------------------------------------------
__int64 objc_retainAutoreleasedReturnValue()
{
  return _objc_retainAutoreleasedReturnValue();
}
// 1000093A0: using guessed type __int64 _objc_retainAutoreleasedReturnValue(void);

// ALL OK, 35 function(s) have been successfully decompiled
